In [5]:
import pandas as pd

df = pd.read_parquet("0000[1].parquet")

df.to_csv("student_placement_raw.csv", index=False)

print("CSV created successfully!")

CSV created successfully!

In [6]:
df.head()

   Internships  CGPA  HistoryOfBacklogs  PlacedOrNot
0            1     8                  1            1
1            0     7                  1            1
2            1     6                  0            1
3            0     8                  1            1
4            0     8                  0            1

In [7]:
df.shape

(2966, 4)

In [8]:
df.columns

Index(['Internships', 'CGPA', 'HistoryOfBacklogs', 'PlacedOrNot'], dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2966 entries, 0 to 2965
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Internships        2966 non-null   int64
 1   CGPA               2966 non-null   int64
 2   HistoryOfBacklogs  2966 non-null   int64
 3   PlacedOrNot        2966 non-null   int64
dtypes: int64(4)
memory usage: 92.8 KB

In [10]:
df.isnull().sum()

Internships          0
CGPA                 0
HistoryOfBacklogs    0
PlacedOrNot          0
dtype: int64

In [11]:
df.describe()

       Internships         CGPA  HistoryOfBacklogs  PlacedOrNot
count  2966.000000  2966.000000        2966.000000  2966.000000
mean      0.703641     7.073837           0.192178     0.552596
std       0.740197     0.967748           0.394079     0.497310
min       0.000000     5.000000           0.000000     0.000000
25%       0.000000     6.000000           0.000000     0.000000
50%       1.000000     7.000000           0.000000     1.000000
75%       1.000000     8.000000           0.000000     1.000000
max       3.000000     9.000000           1.000000     1.000000

In [12]:
df.duplicated().sum()

np.int64(2911)

In [13]:
df.value_counts().head(10)

Internships  CGPA  HistoryOfBacklogs  PlacedOrNot
0            8     0                  1              328
1            8     0                  1              315
0            7     0                  0              274
1            7     0                  0              233
0            6     0                  0              227
1            6     0                  0              211
             7     0                  1               95
2            8     0                  1               88
             6     0                  1               78
0            6     0                  1               76
Name: count, dtype: int64

In [14]:
df.nunique()

Internships          4
CGPA                 5
HistoryOfBacklogs    2
PlacedOrNot          2
dtype: int64

In [15]:
df["PlacedOrNot"].value_counts()

PlacedOrNot
1    1639
0    1327
Name: count, dtype: int64

In [16]:
df["PlacedOrNot"].value_counts(normalize=True) * 100

PlacedOrNot
1    55.259609
0    44.740391
Name: proportion, dtype: float64

In [18]:
df.dtypes

Internships          int64
CGPA                 int64
HistoryOfBacklogs    int64
PlacedOrNot          int64
dtype: object

In [19]:
df["CGPA"].value_counts().sort_index()

CGPA
5     96
6    834
7    956
8    915
9    165
Name: count, dtype: int64

In [20]:
df["Internships"].value_counts().sort_index()

Internships
0    1331
1    1234
2     350
3      51
Name: count, dtype: int64

In [21]:
(df < 0).sum()

Internships          0
CGPA                 0
HistoryOfBacklogs    0
PlacedOrNot          0
dtype: int64

In [22]:
df["CGPA"].between(5, 9).all()

np.True_

In [23]:
df["Internships"].between(0, 3).all()

np.True_

In [24]:
df["HistoryOfBacklogs"].isin([0, 1]).all()

np.True_

In [25]:
df["PlacedOrNot"].isin([0, 1]).all()

np.True_

In [27]:
X = df.drop("PlacedOrNot", axis=1)

In [28]:
y = df["PlacedOrNot"]

In [29]:
X.head()

   Internships  CGPA  HistoryOfBacklogs
0            1     8                  1
1            0     7                  1
2            1     6                  0
3            0     8                  1
4            0     8                  0

0    1
1    1
2    1
3    1
4    1
Name: PlacedOrNot, dtype: int64

In [31]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (2966, 3)
y shape: (2966,)

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (2372, 3)
Testing data: (594, 3)

In [33]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaling completed!")

Scaling completed!

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [35]:
models = {
    "Logistic Regression": LogisticRegression(random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42)
}

print("Models created!")

Models created!

In [36]:
for name, model in models.items():
    model.fit(X_train_scaled, y_train)

print("All models trained successfully!")

All models trained successfully!

In [37]:
predictions = {}

for name, model in models.items():
    predictions[name] = model.predict(X_test_scaled)

print("Predictions completed!")

Predictions completed!

In [38]:
from sklearn.metrics import accuracy_score

for name in models:
    accuracy = accuracy_score(y_test, predictions[name])
    print(name, ":", accuracy)

Logistic Regression : 0.7828282828282829
Decision Tree : 0.8585858585858586
Random Forest : 0.8585858585858586

In [39]:
from sklearn.metrics import classification_report

for name in models:
    print("\n", "="*50)
    print(name)
    print("="*50)
    print(classification_report(y_test, predictions[name]))

 ==================================================
Logistic Regression
==================================================
              precision    recall  f1-score   support

           0       0.77      0.74      0.75       266
           1       0.80      0.82      0.81       328

    accuracy                           0.78       594
   macro avg       0.78      0.78      0.78       594
weighted avg       0.78      0.78      0.78       594


 ==================================================
Decision Tree
==================================================
              precision    recall  f1-score   support

           0       0.78      0.96      0.86       266
           1       0.96      0.78      0.86       328

    accuracy                           0.86       594
   macro avg       0.87      0.87      0.86       594
weighted avg       0.88      0.86      0.86       594


 ==================================================
Random Forest
==================================================
              precision    recall  f1-score   support

           0       0.78      0.96      0.86       266
           1       0.96      0.78      0.86       328

    accuracy                           0.86       594
   macro avg       0.87      0.87      0.86       594
weighted avg       0.88      0.86      0.86       594

In [40]:
from sklearn.metrics import confusion_matrix

for name in models:
    print("\n", name)
    print(confusion_matrix(y_test, predictions[name]))

 Logistic Regression
[[197  69]
 [ 60 268]]

 Decision Tree
[[255  11]
 [ 73 255]]

 Random Forest
[[255  11]
 [ 73 255]]

In [41]:
%pip install mlflow

Collecting mlflow
  Downloading mlflow-3.16.0-py3-none-any.whl.metadata (50 kB)
Collecting mlflow-skinny==3.16.0 (from mlflow)
  Downloading mlflow_skinny-3.16.0-py3-none-any.whl.metadata (50 kB)
Collecting mlflow-tracing==3.16.0 (from mlflow)
  Downloading mlflow_tracing-3.16.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)
Collecting Flask<4 (from mlflow)
  Downloading flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting aiohttp<4,>=3.7.0 (from mlflow)
  Downloading aiohttp-3.14.3-cp311-cp311-win_amd64.whl.metadata (8.5 kB)
Collecting alembic!=1.10.0,<2 (from mlflow)
  Downloading alembic-1.19.2-py3-none-any.whl.metadata (7.3 kB)
Collecting cryptography<51,>=43.0.0 (from mlflow)
  Downloading cryptography-50.0.1-cp311-abi3-win_amd64.whl.metadata (4.3 kB)
Collecting docker<8,>=4.0.0 (from mlflow)
  Downloading docker-7.2.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting huey<4,>=2.5.4 (from mlflow)
  Downloading huey-3.4.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: matplotlib<4 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlflow) (3.11.1)
Requirement already satisfied: numpy<3 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlflow) (2.4.0)
Requirement already satisfied: pandas<4 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlflow) (2.3.3)
Requirement already satisfied: pyarrow<26,>=4.0.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlflow) (22.0.0)
Requirement already satisfied: scikit-learn<2 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlflow) (1.8.0)
Requirement already satisfied: scipy<2 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlflow) (1.16.3)
Collecting skops<1 (from mlflow)
  Downloading skops-0.14.0-py3-none-any.whl.metadata (4.4 kB)
Collecting sqlalchemy<3,>=1.4.0 (from mlflow)
  Downloading sqlalchemy-2.0.52-cp311-cp311-win_amd64.whl.metadata (9.9 kB)
Collecting waitress<4 (from mlflow)
  Downloading waitress-3.0.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: anyio!=4.15.0,<5,>=3.6.2 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlflow-skinny==3.16.0->mlflow) (4.14.2)
Requirement already satisfied: cachetools<8,>=5.0.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlflow-skinny==3.16.0->mlflow) (6.2.4)
Requirement already satisfied: click<9,>=7.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlflow-skinny==3.16.0->mlflow) (8.3.1)
Collecting cloudpickle<4 (from mlflow-skinny==3.16.0->mlflow)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.16.0->mlflow)
  Downloading databricks_sdk-0.137.0-py3-none-any.whl.metadata (44 kB)
Collecting fastapi<1 (from mlflow-skinny==3.16.0->mlflow)
  Downloading fastapi-0.141.1-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: gitpython<4,>=3.1.9 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlflow-skinny==3.16.0->mlflow) (3.1.46)
Collecting importlib_metadata!=4.7.0,<10,>=3.7.0 (from mlflow-skinny==3.16.0->mlflow)
  Downloading importlib_metadata-9.0.1-py3-none-any.whl.metadata (4.5 kB)
Collecting opentelemetry-api<3,>=1.9.0 (from mlflow-skinny==3.16.0->mlflow)
  Downloading opentelemetry_api-1.44.0-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.16.0->mlflow)
  Downloading opentelemetry_proto-1.44.0-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==3.16.0->mlflow)
  Downloading opentelemetry_sdk-1.44.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: packaging<27 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlflow-skinny==3.16.0->mlflow) (25.0)
Requirement already satisfied: protobuf<8,>=3.12.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlflow-skinny==3.16.0->mlflow) (6.33.2)
Collecting pydantic<3,>=2.0.0 (from mlflow-skinny==3.16.0->mlflow)
  Downloading pydantic-2.13.5-py3-none-any.whl.metadata (110 kB)
Collecting python-dotenv<2,>=0.19.0 (from mlflow-skinny==3.16.0->mlflow)
  Downloading python_dotenv-1.2.3-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: pyyaml<7,>=5.1 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlflow-skinny==3.16.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlflow-skinny==3.16.0->mlflow) (2.32.5)
Collecting sqlparse<1,>=0.4.0 (from mlflow-skinny==3.16.0->mlflow)
  Downloading sqlparse-0.6.0-py3-none-any.whl.metadata (6.0 kB)
Collecting starlette<2 (from mlflow-skinny==3.16.0->mlflow)
  Downloading starlette-1.6.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlflow-skinny==3.16.0->mlflow) (4.15.0)
Collecting uvicorn<1 (from mlflow-skinny==3.16.0->mlflow)
  Downloading uvicorn-0.52.4-py3-none-any.whl.metadata (6.6 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4,>=3.7.0->mlflow)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp<4,>=3.7.0->mlflow)
  Using cached frozenlist-1.8.0-cp311-cp311-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading multidict-6.8.0-cp311-cp311-win_amd64.whl.metadata (5.4 kB)
Collecting propcache>=0.2.0 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading propcache-0.5.2-cp311-cp311-win_amd64.whl.metadata (17 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading yarl-1.24.5-cp311-cp311-win_amd64.whl.metadata (107 kB)
Collecting Mako (from alembic!=1.10.0,<2->mlflow)
  Downloading mako-1.4.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: idna>=2.8 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from anyio!=4.15.0,<5,>=3.6.2->mlflow-skinny==3.16.0->mlflow) (3.11)
Requirement already satisfied: colorama in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.16.0->mlflow) (0.4.6)
Requirement already satisfied: cffi>=2.0.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from cryptography<51,>=43.0.0->mlflow) (2.1.1)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.0->mlflow)
  Downloading google_auth-2.58.0-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: urllib3<3,>=1.26 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.0->mlflow) (2.6.3)
Collecting pywin32>=304 (from docker<8,>=4.0.0->mlflow)
  Downloading pywin32-312-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting typing-inspection>=0.4.2 (from fastapi<1->mlflow-skinny==3.16.0->mlflow)
  Downloading typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Collecting annotated-doc>=0.0.2 (from fastapi<1->mlflow-skinny==3.16.0->mlflow)
  Downloading annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: blinker>=1.9.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from Flask<4->mlflow) (1.9.0)
Collecting itsdangerous>=2.2.0 (from Flask<4->mlflow)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: jinja2>=3.1.2 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from Flask<4->mlflow) (3.0.3)
Collecting werkzeug>=3.1.0 (from Flask<4->mlflow)
  Downloading werkzeug-3.1.8-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: gitdb<5,>=4.0.1 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.16.0->mlflow) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.16.0->mlflow) (5.0.2)
Collecting pyasn1-modules>=0.2.1 (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.0->mlflow)
  Using cached pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.12-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Collecting zipp>=3.20 (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.16.0->mlflow)
  Downloading zipp-4.1.0-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: contourpy>=1.0.1 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib<4->mlflow) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib<4->mlflow) (1.5.1)
Requirement already satisfied: pillow>=9 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib<4->mlflow) (12.1.0)
Requirement already satisfied: pyparsing>=3 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib<4->mlflow) (3.3.2)
Collecting opentelemetry-semantic-conventions==0.65b0 (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.16.0->mlflow)
  Downloading opentelemetry_semantic_conventions-0.65b0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: pytz>=2020.1 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas<4->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas<4->mlflow) (2025.3)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=2.0.0->mlflow-skinny==3.16.0->mlflow)
  Downloading annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.5 (from pydantic<3,>=2.0.0->mlflow-skinny==3.16.0->mlflow)
  Downloading pydantic_core-2.46.5-cp311-cp311-win_amd64.whl.metadata (6.7 kB)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.16.0->mlflow) (3.4.4)
Requirement already satisfied: certifi>=2017.4.17 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.16.0->mlflow) (2026.1.4)
Requirement already satisfied: joblib>=1.3.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn<2->mlflow) (3.6.0)
Collecting prettytable>=3.9 (from skops<1->mlflow)
  Downloading prettytable-3.18.0-py3-none-any.whl.metadata (37 kB)
Collecting greenlet>=1 (from sqlalchemy<3,>=1.4.0->mlflow)
  Downloading greenlet-3.5.5-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: h11>=0.8 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from uvicorn<1->mlflow-skinny==3.16.0->mlflow) (0.16.0)
Requirement already satisfied: pycparser in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from cffi>=2.0.0->cryptography<51,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: wcwidth>=0.3.5 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.3)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.0->mlflow)
  Downloading pyasn1-0.6.4-py3-none-any.whl.metadata (8.4 kB)
Downloading mlflow-3.16.0-py3-none-any.whl (11.6 MB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/11.6 MB 6.7 MB/s eta 0:00:02
   ----------- ---------------------------- 3.4/11.6 MB 8.1 MB/s eta 0:00:02
   ------------------- -------------------- 5.5/11.6 MB 9.3 MB/s eta 0:00:01
   ------------------------ --------------- 7.1/11.6 MB 8.6 MB/s eta 0:00:01
   ------------------------ --------------- 7.1/11.6 MB 8.6 MB/s eta 0:00:01
   ------------------------ --------------- 7.1/11.6 MB 8.6 MB/s eta 0:00:01
   -------------------------- ------------- 7.6/11.6 MB 4.8 MB/s eta 0:00:01
   ----------------------------- ---------- 8.4/11.6 MB 4.7 MB/s eta 0:00:01
   -------------------------------- ------- 9.4/11.6 MB 4.7 MB/s eta 0:00:01
   -------------------------------------- - 11.0/11.6 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 11.6/11.6 MB 5.0 MB/s  0:00:02
Downloading mlflow_skinny-3.16.0-py3-none-any.whl (3.7 MB)
   ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
   ------------------------- -------------- 2.4/3.7 MB 11.2 MB/s eta 0:00:01
   ---------------------------------------- 3.7/3.7 MB 9.2 MB/s  0:00:00
Downloading mlflow_tracing-3.16.0-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----------------------- ---------------- 1.0/1.8 MB 5.6 MB/s eta 0:00:01
   ----------------------- ---------------- 1.0/1.8 MB 5.6 MB/s eta 0:00:01
   ---------------------------------- ----- 1.6/1.8 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 2.3 MB/s  0:00:00
Downloading aiohttp-3.14.3-cp311-cp311-win_amd64.whl (481 kB)
Downloading alembic-1.19.2-py3-none-any.whl (267 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading cryptography-50.0.1-cp311-abi3-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   -------- ------------------------------- 0.8/3.8 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.8/3.8 MB 4.2 MB/s eta 0:00:01
   --------------------------- ------------ 2.6/3.8 MB 4.3 MB/s eta 0:00:01
   -------------------------------------- - 3.7/3.8 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 3.7 MB/s  0:00:01
Downloading databricks_sdk-0.137.0-py3-none-any.whl (1.0 MB)
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   -------------------- ------------------- 0.5/1.0 MB 4.2 MB/s eta 0:00:01
   -------------------- ------------------- 0.5/1.0 MB 4.2 MB/s eta 0:00:01
   ------------------------------ --------- 0.8/1.0 MB 907.1 kB/s eta 0:00:01
   ---------------------------------------- 1.0/1.0 MB 1.1 MB/s  0:00:00
Downloading docker-7.2.0-py3-none-any.whl (148 kB)
Downloading fastapi-0.141.1-py3-none-any.whl (131 kB)
Downloading flask-3.1.3-py3-none-any.whl (103 kB)
Downloading flask_cors-6.0.5-py3-none-any.whl (16 kB)
Downloading google_auth-2.58.0-py3-none-any.whl (262 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Downloading graphql_core-3.2.12-py3-none-any.whl (216 kB)
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading huey-3.4.0-py3-none-any.whl (136 kB)
Downloading importlib_metadata-9.0.1-py3-none-any.whl (27 kB)
Downloading multidict-6.8.0-cp311-cp311-win_amd64.whl (51 kB)
Downloading opentelemetry_api-1.44.0-py3-none-any.whl (60 kB)
Downloading opentelemetry_proto-1.44.0-py3-none-any.whl (72 kB)
Downloading opentelemetry_sdk-1.44.0-py3-none-any.whl (137 kB)
Downloading opentelemetry_semantic_conventions-0.65b0-py3-none-any.whl (204 kB)
Downloading pydantic-2.13.5-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.5-cp311-cp311-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   --------------- ------------------------ 0.8/2.0 MB 6.7 MB/s eta 0:00:01
   ------------------------- -------------- 1.3/2.0 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 3.4 MB/s  0:00:00
Downloading python_dotenv-1.2.3-py3-none-any.whl (22 kB)
Downloading skops-0.14.0-py3-none-any.whl (132 kB)
Downloading sqlalchemy-2.0.52-cp311-cp311-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ------------------- -------------------- 1.0/2.2 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 5.1 MB/s  0:00:00
Downloading sqlparse-0.6.0-py3-none-any.whl (50 kB)
Downloading starlette-1.6.0-py3-none-any.whl (75 kB)
Downloading uvicorn-0.52.4-py3-none-any.whl (79 kB)
Downloading waitress-3.0.2-py3-none-any.whl (56 kB)
Downloading yarl-1.24.5-cp311-cp311-win_amd64.whl (97 kB)
Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
Downloading annotated_types-0.8.0-py3-none-any.whl (13 kB)
Using cached frozenlist-1.8.0-cp311-cp311-win_amd64.whl (44 kB)
Downloading greenlet-3.5.5-cp311-cp311-win_amd64.whl (323 kB)
Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Downloading prettytable-3.18.0-py3-none-any.whl (37 kB)
Downloading propcache-0.5.2-cp311-cp311-win_amd64.whl (42 kB)
Using cached pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Downloading pyasn1-0.6.4-py3-none-any.whl (84 kB)
Downloading pywin32-312-cp311-cp311-win_amd64.whl (6.9 MB)
   ---------------------------------------- 0.0/6.9 MB ? eta -:--:--
   ------- -------------------------------- 1.3/6.9 MB 6.7 MB/s eta 0:00:01
   --------------- ------------------------ 2.6/6.9 MB 6.6 MB/s eta 0:00:01
   ------------------------ --------------- 4.2/6.9 MB 6.6 MB/s eta 0:00:01
   --------------------------------- ------ 5.8/6.9 MB 6.8 MB/s eta 0:00:01
   ---------------------------------------- 6.9/6.9 MB 6.5 MB/s  0:00:01
Downloading typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Downloading werkzeug-3.1.8-py3-none-any.whl (226 kB)
Downloading zipp-4.1.0-py3-none-any.whl (10 kB)
Downloading mako-1.4.1-py3-none-any.whl (80 kB)
Installing collected packages: huey, zipp, werkzeug, waitress, typing-inspection, sqlparse, pywin32, python-dotenv, pydantic-core, pyasn1, propcache, prettytable, opentelemetry-proto, opentelemetry-api, multidict, Mako, itsdangerous, greenlet, graphql-core, frozenlist, cloudpickle, annotated-types, annotated-doc, aiohappyeyeballs, yarl, uvicorn, starlette, sqlalchemy, pydantic, pyasn1-modules, opentelemetry-semantic-conventions, importlib_metadata, graphql-relay, Flask, docker, cryptography, aiosignal, skops, opentelemetry-sdk, graphene, google-auth, Flask-CORS, fastapi, alembic, aiohttp, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow

   ----------------------------------------  0/49 [huey]
   ----------------------------------------  0/49 [huey]
   ----------------------------------------  0/49 [huey]
   ----------------------------------------  0/49 [huey]
   ----------------------------------------  0/49 [huey]

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [42]:
import mlflow
import mlflow.sklearn

print("MLflow version:", mlflow.__version__)

MLflow version: 3.16.0

In [43]:
mlflow.set_experiment("Student_Placement_Prediction")
print("MLflow experiment created!")

2026/09/11 00:44:33 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/09/11 00:44:33 INFO mlflow.store.db.utils: Updating database tables
2026/09/11 00:44:37 INFO mlflow.tracking.fluent: Experiment with name 'Student_Placement_Prediction' does not exist. Creating a new experiment.

MLflow experiment created!

In [44]:
for name, model in models.items():

    with mlflow.start_run(run_name=name):

        accuracy = accuracy_score(
            y_test,
            model.predict(X_test_scaled)
        )

        mlflow.log_param("model", name)
        mlflow.log_param("test_size", 0.2)
        mlflow.log_param("random_state", 42)

        mlflow.log_metric("accuracy", accuracy)

        mlflow.sklearn.log_model(
            model,
            "model"
        )

        print(name, "logged with accuracy:", accuracy)

2026/09/11 00:44:39 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Logistic Regression logged with accuracy: 0.7828282828282829

2026/09/11 00:45:19 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Decision Tree logged with accuracy: 0.8585858585858586

2026/09/11 00:45:40 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Random Forest logged with accuracy: 0.8585858585858586

In [48]:
results = {}

for name, model in models.items():
    results[name] = accuracy_score(
        y_test,
        model.predict(X_test_scaled)
    )

best_model_name = max(results, key=results.get)
best_model = models[best_model_name]

print("Best Model:", best_model_name)
print("Best Accuracy:", results[best_model_name])

Best Model: Decision Tree
Best Accuracy: 0.8585858585858586

In [47]:
import joblib

joblib.dump(scaler, "scaler.pkl")
joblib.dump(best_model, "best_model.pkl")

print("Model and scaler saved successfully!")

Model and scaler saved successfully!

In [49]:
from mlflow.models import infer_signature

signature = infer_signature(
    X_train_scaled,
    best_model.predict(X_train_scaled)
)

print("Model signature created!")

Model signature created!

In [58]:
with mlflow.start_run(run_name="Best_Model"):

    accuracy = accuracy_score(
        y_test,
        best_model.predict(X_test_scaled)
    )

    mlflow.log_param("best_model", best_model_name)
    mlflow.log_metric("accuracy", accuracy)

    mlflow.sklearn.log_model(
        best_model,
        "model",
        signature=signature
    )

print("Best model logged to MLflow!")

2026/09/11 00:58:35 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Best model logged to MLflow!

In [51]:
import mlflow
print("MLflow version:", mlflow.__version__)

MLflow version: 3.16.0

In [52]:
mlflow.set_experiment("Student_Placement_Prediction")

print("MLflow experiment created successfully!")

MLflow experiment created successfully!

In [59]:
import mlflow
import mlflow.sklearn
from sklearn.metrics import accuracy_score

for name, model in models.items():

    with mlflow.start_run(run_name=name):

        model.fit(X_train_scaled, y_train)

        predictions = model.predict(X_test_scaled)

        accuracy = accuracy_score(y_test, predictions)

        mlflow.log_param("model", name)
        mlflow.log_metric("accuracy", accuracy)

        mlflow.sklearn.log_model(model, "model")

        print(name, "Accuracy:", accuracy)

print("All models logged to MLflow successfully!")

2026/09/11 00:58:55 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/11 00:59:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Logistic Regression Accuracy: 0.7828282828282829
Decision Tree Accuracy: 0.8585858585858586

2026/09/11 00:59:33 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Random Forest Accuracy: 0.8585858585858586
All models logged to MLflow successfully!

In [60]:
from sklearn.metrics import precision_score

for name in models:
    print(name, "Precision:", precision_score(y_test, models[name].predict(X_test_scaled)))

Logistic Regression Precision: 0.7952522255192879
Decision Tree Precision: 0.9586466165413534
Random Forest Precision: 0.9586466165413534

In [61]:
from sklearn.metrics import recall_score

for name in models:
    print(name, "Recall:", recall_score(y_test, models[name].predict(X_test_scaled)))

Logistic Regression Recall: 0.8170731707317073
Decision Tree Recall: 0.7774390243902439
Random Forest Recall: 0.7774390243902439

In [62]:
from sklearn.metrics import f1_score

for name in models:
    print(name, "F1 Score:", f1_score(y_test, models[name].predict(X_test_scaled)))

Logistic Regression F1 Score: 0.806015037593985
Decision Tree F1 Score: 0.8585858585858586
Random Forest F1 Score: 0.8585858585858586

In [63]:
from sklearn.metrics import confusion_matrix

for name in models:
    print("\n", name)
    print(confusion_matrix(y_test, models[name].predict(X_test_scaled)))

 Logistic Regression
[[197  69]
 [ 60 268]]

 Decision Tree
[[255  11]
 [ 73 255]]

 Random Forest
[[255  11]
 [ 73 255]]

In [64]:
results = {}

for name in models:
    pred = models[name].predict(X_test_scaled)
    results[name] = accuracy_score(y_test, pred)

print(results)

{'Logistic Regression': 0.7828282828282829, 'Decision Tree': 0.8585858585858586, 'Random Forest': 0.8585858585858586}

In [65]:
best_model_name = "Random Forest"
best_model = models[best_model_name]

print("Best Model:", best_model_name)

Best Model: Random Forest

In [66]:
import joblib

joblib.dump(best_model, "best_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("Model and scaler saved successfully!")

Model and scaler saved successfully!

In [67]:
from mlflow.models import infer_signature

signature = infer_signature(
    X_train_scaled,
    best_model.predict(X_train_scaled)
)

print("Model signature created!")

Model signature created!

In [68]:
best_accuracy = accuracy_score(
    y_test,
    best_model.predict(X_test_scaled)
)

print("Best Model:", best_model_name)
print("Best Accuracy:", best_accuracy)

Best Model: Random Forest
Best Accuracy: 0.8585858585858586

In [69]:
print("Files saved:")
import os

print(os.listdir())

Files saved:
['-1.14-windows.xml', '.android', '.aws', '.bash_history', '.cache', '.config', '.dotnet', '.dvc', '.dvcignore', '.eclipse', '.git', '.gitconfig', '.gradle', '.ipynb_checkpoints', '.ipython', '.jdks', '.jupyter', '.keras', '.lemminx', '.lesshst', '.m2', '.matplotlib', '.ms-ad', '.node_repl_history', '.openjfx', '.p2', '.packettracer', '.redhat', '.ssh', '.streamlit', '.templateengine', '.vscode', '.vscode-shared', '0000[1].parquet', 'AndroidStudioProjects', 'AppData', 'Application Data', 'best_model.pkl', 'bgame', 'bgbg', 'bgg', 'bikeegame', 'bikegame', 'bikgame', 'bookingTravel', 'chat-app-backend', 'chat-app-dashboard', 'Cisco Packet Tracer 9.0.0', 'clgProjects', 'Contacts', 'Cookies', 'cpp', 'CrossDevice', 'cscript', 'DaVinci Resolve Media', 'Desktop', 'Documents', 'download.png', 'Downloads', 'Dropbox', 'E-Comm', 'eclipse-workspace', 'Favorites', 'fire base Auth Test', 'formm', 'formvalidation', 'gamee', 'ibisPaint', 'IdeaProjects', 'image editor', 'java', 'js', 'leetcode-proxy', 'Links', 'Local Settings', 'mlflow.db', 'mlops-exp5,231fa04b33.ipynb', 'MLOps_Exp5', 'mlruns', 'MovieApp', 'Music', 'My Documents', 'my-hosted-projects', 'NetHood', 'new', 'New folder', 'New folder (2)', 'New folder (3)', 'newtwitter', 'nodejs-intro', 'node_modules', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{f1470574-09a6-11f0-9f1a-9188033225d7}.TM.blf', 'NTUSER.DAT{f1470574-09a6-11f0-9f1a-9188033225d7}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{f1470574-09a6-11f0-9f1a-9188033225d7}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'package-lock.json', 'package.json', 'Pictures', 'portfolio', 'Postman', 'PrintHood', 'quizApp', 'reactpro', 'react_projects', 'react_series', 'Recent', 'resssume', 'resumeee', 'Saved Games', 'scaler.pkl', 'Searches', 'SendTo', 'source', 'ss', 'Start Menu', 'student_placement_raw.csv', 'system_design_roadmap_without_phase1.pdf', 'tailwind.config.js', 'Templates', 'test-app', 'tulasi-profile.png', 'twi-clone', 'twitter-clone', 'udemy-web-dev', 'udemycertif.pdf', 'Untitled.ipynb', 'videoFlix', 'Videos', 'Week3Lab', 'wishlist', 'Zenitsu wallpaper.jpeg']

In [71]:
with mlflow.start_run(run_name="Random_Forest_Production") as run:
    run_id = run.info.run_id

    accuracy = accuracy_score(
        y_test,
        best_model.predict(X_test_scaled)
    )

    mlflow.log_param("model", "Random Forest")
    mlflow.log_metric("accuracy", accuracy)

    mlflow.sklearn.log_model(
        best_model,
        name="random_forest_model",
        signature=signature
    )

print("Run ID:", run_id)

Run ID: eed8385587064e28ab42ae8bf225334e

In [72]:
registered_model_name = "StudentPlacementPredictionModel"

print(registered_model_name)

StudentPlacementPredictionModel

In [73]:
model_uri = f"runs:/{run_id}/random_forest_model"

registered_model = mlflow.register_model(
    model_uri=model_uri,
    name=registered_model_name
)

print("Model registered successfully!")

Successfully registered model 'StudentPlacementPredictionModel'.
2026/09/11 01:03:15 WARNING mlflow.tracking._model_registry.fluent: Run with id eed8385587064e28ab42ae8bf225334e has no artifacts at artifact path 'random_forest_model', registering model based on models:/m-0422ba3d05074511ae65f2e790d1ff4f instead
Created version '1' of model 'StudentPlacementPredictionModel'.

Model registered successfully!

In [74]:
print("Model Name:", registered_model.name)
print("Model Version:", registered_model.version)

Model Name: StudentPlacementPredictionModel
Model Version: 1

In [75]:
print("MLflow Tracking URI:")
print(mlflow.get_tracking_uri())

MLflow Tracking URI:
sqlite:///C:/Users/chinn/mlflow.db

In [76]:
import mlflow
print(mlflow.get_tracking_uri())

sqlite:///C:/Users/chinn/mlflow.db